settings = {
    "loih": {
        "profile": "loih.prf",
        "airspace": ["lovv.desktop.strepla.openair.txt"],
        "waipoint": ["Austria.cup", "ofm.cup"],
        "map": "ALPS_HighRes.xcm",
        "checklist": "loih.txt",
        "events": "events.xci",
        "plane": "D-5461-18m.xcp",
    },
    "sisteron": {
        "profile": "sisteron.prf",
        "airspace": ["lovv.desktop.strepla.openair.txt"],
        "waipoint": ["ofm.cup"],
        "map": "ALPS_HighRes.xcm",
        "checklist": "sisteron.txt",
        "events": "events.xci",
        "plane": "D-5461-18m.xcp",
    },
    "aac2017": {
        "profile": "wettbewerb.prf",
        "airspace": ["lovv.desktop.strepla.openair.txt"],
        "waipoint": ["Austria.cup", "ofm.cup"],
        "map": "ALPS_HighRes.xcm",
        "checklist": "aac.txt",
        "events": "events.xci",
        "plane": "D-5461-18m.xcp",
    },
    "stm2017": {
        "profile": "wettbewerb.prf",
        "airspace": ["lovv.desktop.strepla.openair.txt"],
        "waipoint": ["Austria.cup", "ofm.cup"],
        "map": "ALPS_HighRes.xcm",
        "checklist": "loih.txt",
        "events": "events.xci",
        "plane": "D-5461-18m.xcp",
    },
}
